title: 诚blog
author: jiangfangcheng
email: jiangfangcheng@oulook.com
description: >-
social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
